[webcam]
device_index = 0
width = 1280
height = 720
default_fps = 10

[email_notification]
enabled = false
smtp_server = "smtp.your-email-provider.com"
smtp_port = "465"  # or "587"
sender_email = "your-email-here@example.com"
sender_password = "your-email-password-here"
receiver_email = "your-personal-email-that-will-receive-notification@example.com"
